apiVersion: v1
kind: Service
metadata:
  name: todo-service
  labels:
    name: todo-service
    app: demo-simple-todo-app
spec:
  ports:
  - port: 8080
    targetPort: 3000
    nodePort: 30001
  type: NodePort
  selector:
     name: simple-todo-app-pod
     app: demo-simple-todo-app