apiVersion: v1
kind: Pod
metadata:
  name: simple-todo-app-pod
  labels:
    name: simple-todo-app-pod
    app: demo-simple-todo-app
spec:
  containers:
  - name: simple-todo-app
    image: shadab024/simple-todo-app:latest
    ports:
         - containerPort: 3000